### ISSUE TITLE
Add section to compare/contrast senders and coroutines

### ISSUE THREAD

**Issue by ericniebler** [brycelelbach/wg21_p2300_std_execution#150]
... and also discuss under what conditions senders can be made awaitable in coroutines, and the hope we get a `std::task` type that makes senders awaitable.

**Comment by cor3ntin** [comment]
Haha, I was going to create this issue.

So the plan is to propose `operator co_await(awaitable_sender)` in a separate paper?
Folks seem to be under the impression that it's two separate things/models so anything that can show that coroutines can be sugar over senders would be great.

Despite the imperfect fit

**Comment by LeeHowes** [comment]
It seemed hard to add it in here without any of the coroutine library types.

The task type should hook into the same scheduler and cancellation propagation machinery that we have here, so co_await in a task should work on any sender. That seems the right order to approach it in.

**Comment by ericniebler** [comment]
>The task type should hook into the same scheduler and cancellation propagation machinery that we have here, so co_await in a task should work on any sender. That seems the right order to approach it in.

I disagree. For any real solution, we would want that ability to automatically propagate stop tokens and schedulers, but that's not necessary for some edifying code to help people understand the basic idea. _Very_ simple `sender_as_awaitable` and `awaitable_as_sender` that does nothing fancy would go a long way to clearing up the fear and uncertainty. We have to dispel the impression that a vote for sender/receiver is a vote against coroutines.

**Comment by lewissbaker** [comment]
> _Very_ simple `sender_as_awaitable` and `awaitable_as_sender` that does nothing fancy would go a long way to clearing up the fear and uncertainty. We have to dispel the impression that a vote for sender/receiver is a vote against coroutines.

I think any examples we show involving coroutines should just have coroutines magically interoperating with senders. We should not see the identifiers “awaitable_as_sender” or “sender_as_awaitable” in the example code.

**Comment by ericniebler** [comment]
Hrm, maybe, but some might find it instructive to see _how_ these things interoperate.

I've had luck teaching someone about senders but showing them how to implement the `as_future` algorithm.

**Comment by cor3ntin** [comment]
@ericniebler The thing is, that does not illustrate a big difference from the networking TS where you can get it to return an awaitable using `use_awaitable` as a completion token.

Certainly, explaining how it works is super interesting but not *the main point*.

I think it would be useful to present, in order of importance

- This model works with coroutines, out of the box, without having to use a different interface. Senders (a subset thereof) are awaitable. and because algorithms are senders, (some) algorithms are awaitable, etc

- Here is how it works. Then to demonstrate that senders can be adapted to a variety of scenarios and existing utilities, like futures using similar implementations. This is super important as it shows that the model is flexible.

- _Then_ explain that there is some mismatch such that senders are strictly more powerful than coroutines, and that coroutines are not sufficient but only once everyone understands that they can use coroutines in most cases.

- Then, maybe try to hammer https://wg21.link/p1745r0 some more, but maybe people have to get a partial solution before they are willing to try and address mismatches

Right now, I don't think everybody is aware they can use coroutines and that may make them warry.

I really think transparent /easy to use (albeit limited) integration with coroutine ought to be a requirement of any asynchronous work, and while I know that it's possible with senders, that point could be made more evident.

**Comment by ericniebler** [comment]
@cor3ntin I am actually agreeing with you. When I suggested showing the adaptation machinery, I was also planning to show an `operator co_await` that made senders automatically awaitable. I was interpreting @lewissbaker's comment as implying that we show how it magically Just Works without showing people how, which I think would just lead to questions.

I do like the approach you outline here. Thanks.
