### ISSUE TITLE
start_detached should use the receiver's allocator

### ISSUE THREAD

**Issue by ericniebler** [brycelelbach/wg21_p2300_std_execution#339]

**Comment by lewissbaker** [comment]
`start_detached()` doesn't take a receiver, though?

**Comment by LeeHowes** [comment]
Presumably async_scope.spawn_future makes this go away because the async_scope's job is managing that allocation, so the scope carries an implied allocator with it (though not one it would propagate up the chain as a receiver query).

If so, the way to close this issue is to switch to using async_scope.

**Comment by ericniebler** [comment]
> `start_detached()` doesn't take a receiver, though?

🤦‍♂️ I may have been thinking of `submit()`, which morphed into `start_detached()`.

So let me change the question: should `start_detached()` optionally take an allocator? And I'll answer my own question: yes, except that we sincerely hope to replace `start_detached()` with a safer interface like @LeeHowes suggests above. So doing nothing for now seems the simplest.
