### ISSUE TITLE
clarification of `receiver` concept and `receiver_of` concept

### ISSUE THREAD

**Issue by huixie90** [brycelelbach/wg21_p2300_std_execution#351]
The `receiver` concept gives the flexibility to specify the error type with `expcetion_ptr` being the default
```
template<class T, class E = exception_ptr>
concept receiver = ...
```

But the `receiver_of` concept forces to use `expcetion_ptr` as the error type
```
template<class T, class... An>
concept receiver_of =
  receiver<T> && ...
```

Is this by design and what is the rationale behind this inconsistency?

**Comment by ericniebler** [comment]
This is intentional, although not all the authors of P2300 agree about this. The intent is that *all* receivers support `exception_ptr` as an error type. A function such as the following:

```c++
template <receiver_of<int> R>
void tag_invoke(connect_t, my_sender const&, R&&);
```

... is constrained to accept a receiver that accepts an `int` as a value and an `exception_ptr` as an error. If a function is going to send another kind of error -- say, `error_code` -- it would look like this:

```c++
template <receiver_of<int> R>
  requires receiver<R, error_code>
void tag_invoke(connect_t, my_sender const&, R&&);
```

That receiver type must accept both `exception_ptr` and `error_code` as errors.
